#!/bin/bash
##########################################################
# Power By Deepin Installer
# Installer DIY By gfdgd xi、为什么您不喜欢熊出没和阿布呢
# WebSize: https://gfdgd-xi.github.io
# 介绍：你可以在这里输入需要在安装过程中需要添加运行的脚本以便执行
##########################################################
# 如果想要的话请删除对应命令前面的 #
# 一般情况下命令越多安装所需时间越长（卡在 81% 的时间），请根据实际情况设置
# 提示：此是在 chroot 环境下操作，所以不要输入不能在 chroot 环境下运行的命令

######### 默认安装
# 先安装镜像内自带的镜像
# 安装需要定制安装的 deb
if [ -d /usr/share/deepin-installer/deb ]; then
    echo 安装自定义 deb
    dpkg -i /usr/share/deepin-installer/deb/*.deb | true
    apt install -f -y | true
fi
if [ -d /media/cdrom/DIY/DEB ]; then
    echo 安装自定义 deb
    dpkg -i /media/cdrom/DIY/DEB/*.deb | true
    apt install -f -y | true
fi
# 判断是否能连接到镜像源
curl https://mirrors.sdu.edu.cn/spark-store-repository --connect-timeout 2 -m 2
if [[ $? == "0" ]]; then
    # 安装星火里面的 QQ、微信（wine 版本）
    # 不使用 aptss，因为在 chroot 环境难以使用
    apt install com.qq.weixin.spark -y | true
else
    # 安装官方应用商店里面的 QQ、微信（wine 版本）
    apt install com.qq.weixin.deepin deepin-mobile-assistant -y | true
fi
# 安装/更新部分程序版本
aptss install com.gitee.deepin-opensource.desktop-entry-editor spark-simple-remote-desktop-accessor ms-core-fonts winfonts uos-remote-assistance spark-deepin-wine-runner spark-store com.uostools.udom timeshift  -y | true
aptss install linuxqq com.gitee.uengine.runner.spark uengine cn.wps.wps-office com.alibabainc.dingtalk -y


###### 常见软件套组
# 安装 Android 模拟器
#apt install com.gitee.uengine.runner.spark uengine -y
# 安装 Microsoft Office 2007 Professional Plus（Wine）全家桶
#apt install com.microsoft.access.deepin spark-microsoftsharepoint spark-microsoft-visio spark-microsoft-powerpoint spark.microsoft.excel spark-microsoft-word -y
# UOS 原生应用全家桶（只移植成功部分）
#apt install org.deepin.chineseime org.deepin.contacts deepin-pc-butler-spark -y
# 安装 winehq stable（下面好几行都需要取消注释）
# apt install winehq-devel -y

###### 单独软件
# Microsoft Edge
#apt install microsoft-edge-stable -y
# 腾讯会议
#apt install wemeet -y
# Visual Studio Code(vscode)
#apt install code -y
# git
#apt install git -y
# Steam
#apt install steam-launcher -y
# 星火商店投稿器
#apt install spark-store-submitter -y
# 酷狗音乐（wine）
#apt install com.kugou.spark -y
# 数学公式字体
#apt install symbol-fonts -y
# TIM
#apt install com.qq.tim.spark -y
# 应用管理器
#apt install com.github.ccc-app-manager -y
# 百度翻译（Linux）
#apt install com.baidu.translateclient -y
# 深度中文输入法
#apt install org.deepin.chineseime -y
# 同花顺免费版（wine7）
#apt install cn.com.10jqka.tonghuashun.spark -y
# Wine游戏助手
#apt install net.winegame.client -y
# 360杀毒
#apt install 360sd -y
# 百度Linux输入法
#apt install fcitx-baidupinyin -y
# 讯飞输入法
#apt install com.iflytek.iflyime -y
# 几何画板（wine6）
#apt install com.jihehuaban.cn -y
# 迅雷(linux版)
#apt install com.xunlei.download -y
# 希沃白板5
#apt install com.seewo.easinote5 -y
# 火绒安全
#apt install cn.huorong.esm -y
# 桌面快捷方式编辑器
#apt install com.gitee.deepin-opensource.desktop-entry-editor -y
# DDE配置助手(oh my dde)
#apt install top.yzzi.youjian -y
# Adobe Illustrator CC 2015（Wine）
#apt install com.sugarcane.adobe.illustrator -y
# Adobe Photoshop CC 2018
#apt install com.sugarcane.adobe.photoshop -y
# Adobe Photoshop CS6
#apt install com.photoshopcs6.deepin -y
# bilibili客户端（Linux）
#apt install io.github.msojocs.bilibili -y
# QQ音乐
#apt install qqmusic -y
# blossom图标主题
#apt install blossom -y
# 官方壁纸分享
#apt install deepin-wallpapers-bbs-spark -y
# 音乐小部件
#apt install top.yzzi.musicwidget -y
# 动态图片屏保
#apt install picture-screensaver -y
# 向日葵远程控制
#apt install com.oray.sunlogin.client -y
# 金山打字通 2008（wine）
#apt install spark-typeeasy -y
# QtScrcpy
#apt install qtscrcpy -y
# 任务栏系统监视器
#apt install dde-dock-monitor-plugin -y
# 必剪（wine）
#apt install com.drawyoo.bcut.spark -y
# 千千音乐（wine）
#apt install com.taihe.music.spark -y
# 深谈（UOS联系人）
#apt install org.deepin.contacts -y
# Microsoft Office Word 2007（wine）
#apt install spark-microsoft-word -y
# Microsoft Office Excel 2007 Professional（wine）
#apt install spark.microsoft.excel -y
# Microsoft Office PowerPoint 2007(wine)
#apt install spark-microsoft-powerpoint -y
# Microsoft Office Visio 2007
#apt install spark-microsoft-visio -y
# Microsoft Office SharePoint Designer 2007
#apt install spark-microsoftsharepoint -y
# Microsoft Office Access 2007 Professional Plus（Wine）
#apt install com.microsoft.access.deepin -y
# CrossOver for deepin
#apt install crossover-deepin -y
# Mind+
#apt install mindplus -y
# PhotoGIMP
#apt install photogimp -y
# PhotoZoom Pro 8（wine）
#apt install spark-photozoom -y
# Spark Wine7 Devel
#apt install spark-wine7-devel -y
# 金山词霸
#apt install com.kingsoft.powerword -y
# 金山PDF（wine）
#apt install com.wpspdf.spark -y
# 金山词霸2022（Wine）
#apt install com.iciba.powerword.spark -y
# Bandizip
#apt install com.deepin.bandizip -y
# 系统助手
#apt install sysbro -y
# qemu
#apt install qemu-system -y
# 电脑管家（不推荐安装）
#apt install deepin-pc-butler-spark -y
# 更新系统（建议系统安装后自行手动更新）
#apt dist-upgrade
