#!/bin/sh
set -e
# Automatically added by dh_systemd_start/13.3.3~bpo10+1
if [ -d /run/systemd/system ] && [ "$1" = remove ]; then
	systemctl --system daemon-reload >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_systemd_enable/13.3.3~bpo10+1
if [ "$1" = "remove" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper mask 'deepin-installer.service' >/dev/null || true
	fi
fi

if [ "$1" = "purge" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper purge 'deepin-installer.service' >/dev/null || true
		deb-systemd-helper unmask 'deepin-installer.service' >/dev/null || true
	fi
fi
# End automatically added section
